mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from courses import views


urlpatterns = [
    path("", views.search_course, name="search_course"),
    path("courses/", include("courses.urls", namespace="courses")),
    path("admin/", admin.site.urls),
    path("user/", include("userprofile.urls")),
    path("comment/", include("comment.urls", namespace="comment")),
]

mysite/userprofile/urls.py
from django.urls import path
from . import views

app_name = "userprofile"

urlpatterns = [
    # 用户页面
    path("user_page/", views.user_page, name="user_page"),
    # 用户登录
    path("login/", views.user_login, name="login"),
    # 用户退出
    path("logout/", views.user_logout, name="logout"),
    # 用户注册
    path("register/", views.user_register, name="register"),
    # 邮箱验证
    path('activate/<uidb64>/<token>/', views.ActivateView.as_view(), name='activate'),
]

mysite/templates/share_layout/banner.html
<div class="updates-banner invisible">
    <div class="container">
      
    </div>
    <div
      tabindex="0"
      role="button"
      title="Dismiss this update"
      class="dismiss-btn"
      id="banner-dismiss-btn"
    >
      <span class="sr-only">Dismiss this update</span
      ><span aria-hidden="true" class="glyph-icon"></span>
    </div>
  </div>

mysite/templates/share_layout/base.html
{% load static %}

<html lang="ja">
  <head>
    <meta charset="utf-8" />

    <title>{% block title %}{% endblock %}</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    {% block head %}{% endblock %}
  </head>

  <body>
    {% include 'share_layout/nav.html' %}
    
    {% include 'share_layout/banner.html' %}

    <div role="main" id="main-content">
      <div class="container body-content docs blog">
        {% block contents %}{% endblock %}
      </div>
    </div>

    {% block footer %}{% endblock %}

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

mysite/templates/share_layout/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Course</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        <li class="nav-item">
          <a class="nav-link active">Placehoder</a>
        </li>
      </ul>

      <form class="d-flex form-inline my-2 my-lg-0" action="/" method="post">
        {% csrf_token %} 
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="searchCourse" id="searchCourse">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </li>
    {% if user.is_authenticated %}
    <!-- 如果用户已经登录，则显示用户名下拉框 -->
    <li class="nav-item dropdown navbar-nav">
      <a
        class="nav-link dropdown-toggle nav-link active"
        href="#"
        id="navbarDropdown"
        role="button"
        data-bs-toggle="dropdown"
        aria-expanded="false"
      >
        {{ user.username }}
      </a>
      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <li>
          <a class="dropdown-item" href='{% url "userprofile:user_page" %}'
            >my page</a
          >
        </li>
        <li><hr class="dropdown-divider" /></li>
        <li>
          <a class="dropdown-item" href='{% url "userprofile:logout" %}'
            >ログアウト</a
          >
        </li>
      </ul>
    </li>
    <!-- 如果用户未登录，则显示 “登录” -->
    {% else %}
    <li class="nav-item navbar-nav">
      <a class="nav-link active" href="{% url 'userprofile:login' %}">ログイン</a>
    </li>
    <!-- if 语句在这里结束 -->
    {% endif %}
    </div>
  </div>
</nav>