mysite/comment/urls.py
from django.urls import path

from . import views

app_name = "comment"

urlpatterns = [
    # 发表评论
    path("post-comment/<int:course_id>/", views.post_comment, name="post_comment"),
    path(
        "delete-comment/<int:comment_id>/", views.delete_comment, name="delete_comment"
    ),
]

mysite/courses/urls.py
from django.urls import path

from . import views

app_name = "courses"

urlpatterns = [
    # ex: /courses/
    # path('', views.index, name='index'),
    # ex: /courses/5/
    path("<int:course_id>/", views.detail, name="detail"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from courses import views


urlpatterns = [
    path("", views.search_course, name="search_course"),
    path("courses/", include("courses.urls", namespace="courses")),
    path("admin/", admin.site.urls),
    path("user/", include("userprofile.urls")),
    path("comment/", include("comment.urls", namespace="comment")),
]

mysite/userprofile/urls.py
from django.urls import path
from . import views

app_name = "userprofile"

urlpatterns = [
    # 用户页面
    path("user_page/", views.user_page, name="user_page"),
    # 用户登录
    path("login/", views.user_login, name="login"),
    # 用户退出
    path("logout/", views.user_logout, name="logout"),
    # 用户注册
    path("register/", views.user_register, name="register"),
    # 邮箱验证
    path('activate/<uidb64>/<token>/', views.ActivateView.as_view(), name='activate'),
]

mysite/courses/models.py
from django.db import models
from userprofile.models import Profile

from django.urls import reverse


class Course(models.Model):
    course_name = models.CharField(max_length=200)
    teacher_name = models.CharField(max_length=200)
    class_hours = models.CharField(max_length=200)
    department = models.CharField(max_length=200)
    course_form = models.CharField(max_length=200)
    year_semester = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.course_name

    # 获取文章地址
    def get_absolute_url(self):
        return reverse("course:detail", args=[self.id])

mysite/courses/forms.py
from django import forms


class SearchForm(forms.Form):
    searchCourse = forms.CharField()

mysite/courses/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from userprofile.models import Profile
from comment.models import Comment
from django.contrib.auth.models import User

from .models import Course
from .forms import SearchForm


# def index(request):
#     course_list = Course.objects.order_by('-pub_date')[:5]
#     context = {'course_list': course_list}
#     return render(request, 'courses/index.html', context)


def detail(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    # author = get_object_or_404(Profile, pk=(request.user.id - 1))
    comments = Comment.objects.filter(course=course_id)
    form = SearchForm()
    context = {"course": course, "form": form, "comments": comments}
    return render(request, "courses/detail.html", context)


def search_course(request):
    if request.method == "POST":
        search_form = SearchForm(data=request.POST)
        if search_form.is_valid():
            data = search_form.cleaned_data
            course_list = Course.objects.filter(course_name__icontains=data["searchCourse"])
            context = {"course_list": course_list}
            return render(request, "courses/index.html", context)
    # if a GET (or any other method) we'll create a blank form
    else:
        search_form = SearchForm()
        course_list = Course.objects.order_by('?')[:12]
    return render(request, "courses/home.html", {"form": search_form, "course_list": course_list})

mysite/templates/courses/detail.html
{% extends 'share_layout/base.html' %} {% block contents %}
<div class="col-9">
  <h1>{{ course.course_name }}</h1>
  <ul>
    <li>{{ course.teacher_name }}</li>
    <li>{{ course.class_hours }}</li>
    <li>{{ course.course_form }}</li>
    <li>{{ course.year_semester }}</li>
  </ul>

  <!-- 显示评论 -->
  <div>
    {% for comment in comments %}
    <hr />
    <p>
      <strong style="color: pink"> {{ comment.user }} </strong> 
      <span style="color: green">
        {{ comment.pub_date|date:"Y-m-d" }}
      </span>
      ：
    </p>
    <pre style="font-family: inherit; font-size: 1em">{{ comment.body }}</pre>
    {% endfor %}
  </div>
  <!-- 发表评论 -->
  <hr />
  {% if user.is_authenticated %}
  <div>
    <form action="{% url 'comment:post_comment' course.id %}" method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label for="body">
          <strong> コメント： </strong>
        </label>
        <textarea
          type="text"
          class="form-control"
          id="body"
          name="body"
          rows="2"
        ></textarea>
      </div>
      <!-- 提交按钮 -->
      <button type="submit" class="btn btn-primary">送信</button>
    </form>
  </div>
  <br />
  {% else %}
  <br />
  <h5 class="row justify-content-center">
    <a href="{% url 'userprofile:login' %}">ログイン</a>
  </h5>
  <br />
  {% endif %}
</div>

{% endblock %}

mysite/templates/courses/home.html
{% extends 'share_layout/base.html' %} {% block title %}HOME{% endblock %} {% block contents %}

<div class="row col-lg-8 col-lg-offset-4 col-sm-6 col-sm-offset-3 col-xs-8 col-xs-offset-2">
  <form action="/" method="post">
    {% csrf_token %}
    <div class="input-group flex-nowrap">
      <input type="search" class="form-control" name="searchCourse" id="searchCourse" />
      <input type="submit" value="search"  class='btn btn-outline-success'/>
    </div>
  </form>
</div>

<div class="row" rows="3"></div>

<div class="container">
  <ul>
    <div class="row">
      {% for course in course_list %}
      <div class="col-sm-6 col-xl-3">
        <div class="shadow-sm p-3 mb-5 bg-white rounded card card__one" style="width: 100%;">
          <div class="card__desc">
            <h4 style="overflow: hidden; 
            white-space:nowrap;
            text-overflow:ellipsis;"><a href="/courses/{{ course.id }}/">{{ course.course_name }}</a></h4>
            <p>{{ course.teacher_name }}</p>
            <p class="card_text">{{ course.class_hours }}</p>
            {% if course.course_form != " " %}
            <p style="overflow: hidden; 
            white-space:nowrap;
            text-overflow:ellipsis;">{{ course.course_form }}</p>
            {% else %}
            <p style="overflow: hidden; 
            white-space:nowrap;
            text-overflow:ellipsis;">なし</p>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </ul>
</div>

{% endblock %}

mysite/templates/courses/index.html
{% extends 'share_layout/base.html' %} {% block title %}授業一覧{% endblock %}
{% block contents %}
<div class="row" rows="3"></div>
{% if course_list %}
<div class="container">
  <ul>
    <div class="row">
      {% for course in course_list %}
      <div class="col-sm-6 col-xl-3">
        <div class="shadow-sm p-3 mb-5 bg-white rounded card card__one" style="width: 100%;">
          <div class="card__desc">
            <h4 style="overflow: hidden; 
            white-space:nowrap;
            text-overflow:ellipsis;"><a href="/courses/{{ course.id }}/">{{ course.course_name }}</a></h4>
            <p>{{ course.teacher_name }}</p>
            <p class="card_text">{{ course.class_hours }}</p>
            {% if course.course_form != " " %}
            <p style="overflow: hidden; 
            white-space:nowrap;
            text-overflow:ellipsis;">{{ course.course_form }}</p>
            {% else %}
            <p style="overflow: hidden; 
            white-space:nowrap;
            text-overflow:ellipsis;">なし</p>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </ul>
</div>

{% else %}
<p>検索する授業はありません。</p>
{% endif %} {% endblock %}