mysite/comment/urls.py
from django.urls import path

from . import views

app_name = "comment"

urlpatterns = [
    # 发表评论
    path("post-comment/<int:course_id>/", views.post_comment, name="post_comment"),
    path(
        "delete-comment/<int:comment_id>/", views.delete_comment, name="delete_comment"
    ),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from courses import views


urlpatterns = [
    path("", views.search_course, name="search_course"),
    path("courses/", include("courses.urls", namespace="courses")),
    path("admin/", admin.site.urls),
    path("user/", include("userprofile.urls")),
    path("comment/", include("comment.urls", namespace="comment")),
]

mysite/userprofile/urls.py
from django.urls import path
from . import views

app_name = "userprofile"

urlpatterns = [
    # 用户页面
    path("user_page/", views.user_page, name="user_page"),
    # 用户登录
    path("login/", views.user_login, name="login"),
    # 用户退出
    path("logout/", views.user_logout, name="logout"),
    # 用户注册
    path("register/", views.user_register, name="register"),
    # 邮箱验证
    path('activate/<uidb64>/<token>/', views.ActivateView.as_view(), name='activate'),
]

mysite/comment/models.py
from django.db import models

from userprofile.models import Profile
from courses.models import Course
from django.contrib.auth.models import User


# 博文的评论
class Comment(models.Model):
    course = models.ForeignKey(
        Course,
        on_delete=models.CASCADE,
    )

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )

    body = models.TextField(max_length=2000)
    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('pub_date',)

    def __str__(self):
        return self.body[:20]

mysite/userprofile/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
import datetime

# 引入内置信号
from django.db.models.signals import post_save

# 引入信号接收器的装饰器
from django.dispatch import receiver


# 用户扩展信息
class Profile(models.Model):
    # 与 User 模型构成一对一的关系
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    # 学号
    number = models.CharField(max_length=10, blank=True)
    # 个人简介
    bio = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return "user {}".format(self.user.username)


# 信号接收函数，每当新建 User 实例时自动调用
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


# 信号接收函数，每当更新 User 实例时自动调用
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class EmailVerifyRecord(models.Model):
    # 验证码
    code = models.CharField(max_length=20, verbose_name=u"验证码")
    email = models.EmailField(max_length=50, verbose_name=u"邮箱")
    # 包含注册验证和找回验证
    send_type = models.CharField(
        verbose_name=u"验证码类型",
        max_length=10,
        choices=(("register", u"注册"), ("forget", u"找回密码")),
    )
    send_time = models.DateTimeField(verbose_name=u"发送时间", default=datetime.date)

    class Meta:
        verbose_name = u"邮箱验证码"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return "{0}({1})".format(self.code, self.email)

mysite/userprofile/forms.py
# 引入表单类
from django import forms

# 引入 User 模型
from django.contrib.auth.models import User

from django.conf import settings
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode


def get_activate_url(user):
    uid = urlsafe_base64_encode(force_bytes(user.pk))
    token = default_token_generator.make_token(user)
    return settings.FRONTEND_URL + "/user/activate/{}/{}/".format(uid, token)


# 登录表单，继承了 forms.Form 类
class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


# 注册用户表单
class UserRegisterForm(forms.ModelForm):
    # 复写 User 的密码
    password = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = ("username", "email")

    # 对两次输入的密码是否一致进行检查
    def clean_password2(self):
        data = self.cleaned_data
        if data.get("password") == data.get("password2"):
            return data.get("password")
        else:
            raise forms.ValidationError("密码输入不一致,请重试。")


def activate_user(uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except Exception:
        return False

    if default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        return True

    return False

mysite/userprofile/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .forms import UserLoginForm, UserRegisterForm, get_activate_url, activate_user
from django.core.mail import send_mail
from django.views.generic import TemplateView

from django.contrib.auth.models import User
from .models import Profile

# 用户主页
@login_required(login_url="/userprofile/login/")
def user_page(request):
    context = {"user": request.user}
    return render(request, "userprofile/mypage.html", context)


# 用户登录
def user_login(request):
    if request.method == "POST":
        user_login_form = UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            # .cleaned_data 清洗出合法数据
            data = user_login_form.cleaned_data
            # 检验账号、密码是否正确匹配数据库中的某个用户
            # 如果均匹配则返回这个 user 对象
            user = authenticate(username=data["username"], password=data["password"])
            if get_object_or_404(User, username=data["username"]).is_active:
                if user:
                    # 将用户数据保存在 session 中，即实现了登录动作
                    login(request, user)
                    return redirect("userprofile:user_page")
                else:
                    return render(request, "userprofile/sendemail.html", {"content": "ユーザー名またパスワード入力間違い"})
            else:
                return render(request, "userprofile/sendemail.html", {"content": "メールで認証してください"})
        else:
            return render(request, "userprofile/sendemail.html", {"content": "ユーザー名またパスワード入力間違い"})
    elif request.method == "GET":
        user_login_form = UserLoginForm()
        context = {"form": user_login_form}
        return render(request, "userprofile/login.html", context)
    else:
        return HttpResponse("GETとPOSTミス")


# 用户登出
def user_logout(request):
    logout(request)
    return redirect("/")


# 用户注册
def user_register(request):
    if request.method == "POST":
        user_register_form = UserRegisterForm(data=request.POST)
        if user_register_form.is_valid():
            # 取出email和password
            user_name = request.POST["username"]
            number = request.POST["number"]
            email = number + "@gmail.com"
            # 实例化用户，然后赋值
            new_user = User()
            new_user.username = user_name
            new_user.email = email
            new_user.number = number
            # 设置密码
            new_user.set_password(user_register_form.cleaned_data["password"])
            # 新建用户为非活跃用户，可通过验证变为活跃用户
            new_user.is_active = False
            new_user.save()
            new_user = User.objects.get(username=user_name)
            new_user.profile.number = number
            # 保存好数据后立即登录并返回博客列表页面
            # login(request, new_user)
            # 此处加入了邮箱验证的手段
            activate_url = get_activate_url(new_user)
            message = message_template + activate_url
            new_user.email_user(subject, message)
            return render(request, "userprofile/sendemail.html", {"content": "ご登録ありがとうございます。メールで認証してください"})
        else:
            return HttpResponse("注册表单输入有误。请重新输入~")
    elif request.method == "GET":
        user_register_form = UserRegisterForm()
        context = {"form": user_register_form}
        return render(request, "userprofile/register.html", context)
    else:
        return HttpResponse("请使用GET或POST请求数据")


class ActivateView(TemplateView):
    template_name = "userprofile/activate.html"
    
    def get(self, request, uidb64, token, *args, **kwargs):
        # 認証トークンを検証して、
        result = activate_user(uidb64, token)
        # コンテクストのresultにTrue/Falseの結果を渡します。
        return super().get(request, result=result, **kwargs)

subject = "登録確認"
message_template = """
ご登録ありがとうございます。
以下URLをクリックして登録を完了してください。

"""

mysite/templates/userprofile/activate.html
{% extends "share_layout/base.html" %}
{% block contents %}
{% if result %}
    <p>認証に成功しました。</p>
    <a class="nav-link" href="{% url 'userprofile:login' %}">ログイン</a>
{% else %}
    <p>無効なリンクです。</p>
{% endif %}
{% endblock %}

mysite/templates/userprofile/login.html
{% extends 'share_layout/base.html' %} 

{% block title %} ログイン {% endblock title %} 

{% block contents %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <br>
    <h5><a href='{% url "userprofile:register" %}'>会員登録</a></h5>
    <br>
      <form method="post" action=".">
        {% csrf_token %}
        <!-- 账号 -->
        <div class="form-group">
          <label for="username">ユーザー名</label>
          <input
            type="text"
            class="form-control"
            id="username"
            name="username"
          />
        </div>
        <!-- 密码 -->
        <div class="form-group">
          <label for="password">パスワード</label>
          <input
            type="password"
            class="form-control"
            id="password"
            name="password"
          />
        </div>
        <!-- 提交按钮 -->
        <button type="submit" class="btn btn-primary">ログイン</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

mysite/templates/userprofile/mypage.html
{% extends 'share_layout/base.html' %} {% block contents %}
<h1>{{ user.username }}</h1>
{% for comment in user.comment_set.all %}
<hr />
<li>
  <a href="/courses/{{ comment.course.id }}/"
    >{{ comment.course.course_name }}</a
  >
  : {{ comment.body }}
</li>
<form action="{% url 'comment:delete_comment' comment.id %}" method="POST">
  {% csrf_token %}
  <!-- 删除按钮 -->
  <button type="submit" class="btn btn-dark">delete</button>
</form>
{% endfor %} {% endblock %}

mysite/templates/userprofile/register.html
{% extends "share_layout/base.html" %}
{% block title %} 登録 {% endblock title %}
{% block contents %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <!-- 账号 -->
                <div class="form-group col-md-4">
                    <label for="username">ユーザー名</label>
                    <input type="text" class="form-control" id="username" name="username" required>
                </div>
                <!-- 学籍番号 -->
                <div class="form-group col-md-4">
                    <label for="number">学籍番号(现在用gmail测试，输入@gmail前面的名字，将自动给你的gmail发送确认邮件)</label>
                    <input type="text" class="form-control" id="number" name="number">
                </div>
                <!-- 密码 -->
                <div class="form-group col-md-4">
                    <label for="password">パスワード</label>
                    <input type="password" class="form-control" id="password" name="password" required>
                </div>
                <!-- 确认密码 -->
                <div class="form-group col-md-4">
                    <label for="password2">確認のためもう一度パスワードを入力してください</label>
                    <input type="password" class="form-control" id="password2" name="password2" required>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">登録</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mysite/templates/userprofile/sendemail.html
{% extends "share_layout/base.html" %}
{% block contents %}

<p>{{ content }}</p>

{% endblock %}